apiVersion: v1
kind: Service
metadata:
  name: prokure-seller
  labels:
    name: prokure-seller
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    name: prokure-seller
